version: "3"

services:
  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=ticketbird
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ticketbird
    restart: unless-stopped

  bot:
    image: rg.nl-ams.scw.cloud/dreamexposure/ticketbird:latest
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/bot-config:/ticketbird/bot
    working_dir: /ticketbird/bot
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  ticketbird_data: {}
