version: "3"

services:
  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # This is only for local debugging and development. DO NOT USE IN PRODUCTION!!!!!
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=ticketbird
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ticketbird
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  bot:
    image: rg.nl-ams.scw.cloud/dreamexposure/ticketbird:latest
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./.docker/bot-config:/ticketbird/bot
    working_dir: /ticketbird/bot
    depends_on:
      - mysql
      - redis

volumes:
  ticketbird_data: {}
